let engine;
let resolveQueue = [];

let pvLines = {};

function getBestMove(fen, depth = 1, multiPV = 1) {
    if (!engine) {
        engine = new Worker("/stockfish.js");

        engine.onmessage = (e) => {
            const line = e.data;

            if (line.includes("multipv")) {
                const match = line.match(/multipv (\d+).* pv ([a-h1-8]+)/);
                if (match) {
                    const index = match[1];
                    const move = match[2];

                    pvLines[index] = move;
                }
            }

            if (line.startsWith("bestmove")) {
                const bestMove = line.split(" ")[1];

                const moves = Object.values(pvLines);

                const pool = moves.length ? moves : [bestMove];

                const chosen =
                    pool[Math.floor(Math.random() * Math.min(pool.length, multiPV))];

                resolveQueue.shift()?.(chosen);

                pvLines = {};
            }
        };

        engine.postMessage("uci");
        engine.postMessage("isready");

        engine.postMessage("setoption name Skill Level value 0");
        engine.postMessage("setoption name Contempt value 100");
    }

    return new Promise((resolve) => {
        resolveQueue.push(resolve);

        engine.postMessage(`setoption name MultiPV value ${multiPV}`);

        engine.postMessage(`position fen ${fen}`);
        engine.postMessage(`go depth ${depth}`);
        // engine.postMessage(`go movetime 50`);
    });
}

export function useStockfish() {
    return { getBestMove, getRandomName }
}

const names = [
    "EchoNova",
    "LunarPulse",
    "SilentOrbit",
    "NeonTrace",
    "VoidSignal",
    "FrostByte",
    "CosmicShift",
    "ShadowRelay",
    "PixelDrift",
    "NightVector",
    "NovaFable",
    "StaticBloom",
    "PrismEcho",
    "GhostCircuit",
    "AuraFrame",
    "DigitalDawn",
    "Starbounder",
    "FluxHaven",
    "SolarWhisper",
    "PhantomKey",
    "OrbitMuse",
    "VelvetSignal",
    "ByteHarbor",
    "AstralNote",
    "NeonHorizon",
    "QuietSpark",
    "MoonCipher",
    "ZenithPath",
    "DreamProtocol",
    "FadeLogic",
    "PulseAnchor",
    "CrystalNode",
    "VoidPetal",
    "EchoSpire",
    "RiftCaller",
    "GlowSyntax",
    "SkyFragment",
    "LucidRelay",
    "FrostSignal",
    "NovaThread",
    "PixelWarden",
    "LunarIndex",
    "StaticComet",
    "ShadowMetric",
    "EtherField",
    "PrismRoute",
    "SilentBeacon",
    "StarChroma",
    "DigitalMyth",
    "OrbitBloom",
    "KeyboardGremlin",
    "LaggyWizard",
    "MicMutedAgain",
    "OopsWrongChat",
    "PingPanic",
    "SnackOverlord",
    "TypoChampion",
    "WiFiSorcerer",
    "BufferingHuman",
    "AFKLegend",
    "CapsLockHero",
    "ChairRespawned",
    "PotatoFPS",
    "ErrorLaughing",
    "BrbExistential",
    "SpamSandwich",
    "UninstalledBrain",
    "AccidentalGenius",
    "MomSaidDinner",
    "GlitchSnacker",
    "Laugh.exe",
    "NotASpyTrustMe",
    "ProbablyOffline",
    "LowBatteryMood",
    "ClickedWrong",
    "SlightlyConfused",
    "ForgotMyPassword",
    "MemeInProgress",
    "LaggingIRL",
    "SnackCooldown",
    "VoiceCrackPro",
    "ChatGremlin",
    "JustOneMoreGame",
    "NPCEnergy",
    "MissedTheJoke",
    "SuspiciouslyQuiet",
    "SendHelpPls",
    "WrongEmote",
    "KeyboardPanic",
    "AlmostAFK",
    "SarcasmLoading",
    "PanicTyping",
    "BufferingLaughs",
    "MicEchoVictim",
    "OopsAllCaps",
    "DiscordClownery",
    "Error404Sleep",
    "JokeOnCooldown",
    "LagApologist",
    "BrainNotFound",
    "MochiEcho",
    "BunnyStatic",
    "PeachSignal",
    "SoftOrbit",
    "StarryNibble",
    "CloudPetal",
    "HoneyPixel",
    "CozyNova",
    "SugarWhisper",
    "LunaMuffin",
    "BlushComet",
    "BerryGlow",
    "DreamyPaws",
    "VanillaSpark",
    "SnuggleByte",
    "PetalPing",
    "KawaiiOrbit",
    "SweetLag",
    "PuffySignal",
    "MoonBean",
    "PastelEcho",
    "CherryStatic",
    "CozyWisp",
    "MarshmallowKey",
    "BunnyPulse",
    "SoftBloom",
    "PeachesOnline",
    "GlowSprinkle",
    "BabyNova",
    "StarryCrumbs",
    "LilacPing",
    "SugarDrift",
    "PlushOrbit",
    "DreamyDot",
    "HoneyLag",
    "PinkComet",
    "MuffinSignal",
    "GentleSpark",
    "CloudNibble",
    "CozyCircuit",
    "SoftPeony",
    "BunnySyntax",
    "BlushPixel",
    "PastelWarden",
    "MoonieByte",
    "SnaccStar",
    "SweetHorizon",
    "CuddleTrace",
    "SprinkleGlow",
    "TinyOrbit",
    "EchoSpark",
    "NeonLoop",
    "QuickNova",
    "PulseRay",
    "SnapOrbit",
    "VibeShift",
    "FlashPixel",
    "GlowDash",
    "LunarPop",
    "SwiftSignal",
    "NovaBeat",
    "ClickAura",
    "BuzzFrame",
    "DriftSnap",
    "PulseMint",
    "EchoDash",
    "FlickerRay",
    "ZoomNova",
    "PopCipher",
    "BlinkHaven",
    "VividLoop",
    "SparkMode",
    "GlowSprint",
    "RapidMuse",
    "SnapComet",
    "FreshPulse",
    "NeonBeat",
    "DashOrbit",
    "SignalPop",
    "CrispNova",
    "EchoFlick",
    "BuzzOrbit",
    "FlashMuse",
    "LoopSpark",
    "SwiftAura",
    "GlowClick",
    "BlinkNova",
    "PulseDash",
    "SnapSignal",
    "QuickComet",
    "PopHorizon",
    "NeonShift",
    "VibeSprint",
    "EchoZoom",
    "FreshLoop",
    "DashCipher",
    "SparkRelay",
    "ClickNova",
    "BlinkPulse",
    "RapidEcho",
    "InkedOrbit",
    "MythicSignal",
    "VelvetSyntax",
    "LunarFable",
    "NeonParadox",
    "QuietAlchemy",
    "PrismWarden",
    "EchoMyth",
    "SolarRiddle",
    "VoidCanvas",
    "AstralScript",
    "DreamForge",
    "PixelAlchemy",
    "ShadowVerse",
    "EtherBloom",
    "CosmicWhisper",
    "LucidMythos",
    "StaticFable",
    "NovaPoetry",
    "RiftMuse",
    "DigitalOracle",
    "NightGlyph",
    "HaloCipher",
    "StarRelic",
    "FluxLegend",
    "DreamSyntax",
    "MoonArtifact",
    "PrismLore",
    "VoidSonnet",
    "NeonChronicle",
    "MythicRelay",
    "QuietNova",
    "AstralInk",
    "SolarFiction",
    "PixelMyth",
    "EchoTale",
    "VelvetOrbit",
    "CosmicScript",
    "PhantomLore",
    "DreamRift",
    "StaticVerse",
    "LunarFiction",
    "EtherNarrative",
    "NovaGlyph",
    "ShadowChronos",
    "PrismSaga",
    "LucidFable",
    "DigitalMythic",
    "VoidStory",
    "StarAlchemy",
    "OrbitRift",
    "SilentNovae",
    "EchoFracture",
    "VoidLantern",
    "PrismDrifter",
    "LunarOffset",
    "StaticMirage",
    "NeonHollow",
    "AstralMargin",
    "PixelCinder",
    "ShadowIsle",
    "FluxNomad",
    "EtherTrail",
    "NovaUnderscore",
    "FrostMirage",
    "GhostHarbor",
    "SolarDetour",
    "QuietVector",
    "SignalRaven",
    "OrbitAfterglow",
    "LucentVoid",
    "PixelHaze",
    "NightIndex",
    "RiftMariner",
    "EchoThorn",
    "HaloDrift",
    "StaticUndertone",
    "LunarFringe",
    "NovaWaypoint",
    "PrismDetour",
    "ShadowSplice",
    "VoidCrescent",
    "SignalEmber",
    "AstralSidepath",
    "PixelNomicon",
    "EtherMargin",
    "FrostWaypoint",
    "NeonBacktrail",
    "EchoHinterland",
    "OrbitSilhouette",
    "LucidFracture",
    "StaticWaypoint",
    "SolarUndertow",
    "GhostContour",
    "NovaRemainder",
    "PrismAfterimage",
    "NightWaypoint",
    "VoidOutskirt",
    "SignalResidue",
    "LunarAftertone",
    "StarkSignal",
    "NeoOrbit",
    "PixelSkywalker",
    "WandaStatic",
    "LokiLag",
    "MatrixEcho",
    "ArcanePulse",
    "GothamDrift",
    "JediSyntax",
    "SonicAfterimage"
]

function getRandomName() {
    return names[Math.floor(Math.random() * names.length)];
}